import os

os.system("cat README")
os.system("javac Pentago.java enhanced_mcts.java")
os.system("make")
os.system("echo Running the tests:")
os.system("echo Started at")
os.system("date +'%I:%M %p'")
os.system("./EnhancedMCTS random W .5 100")
os.system("./EnhancedMCTS random B .5 100")
os.system("date +'%I:%M %p'")
os.system("./EnhancedMCTS minimax W 1 30")
os.system("./EnhancedMCTS minimax B 1 30")
os.system("date +'%I:%M %p'")
os.system("./EnhancedMCTS mcts W .5 30")
os.system("./EnhancedMCTS mcts B .5 30 ")
os.system("date +'%I:%M %p'")
os.system("./EnhancedMCTS time W 2 20 .5")
os.system("./EnhancedMCTS time B 2 20 .5")
os.system("echo Terminated at")
os.system("date +'%I:%M %p'")